package SubsequencesAndSubsets

import (
	"fmt"
	"goplay/SubsequencesAndSubsets/Assignment"
)


func SubsequencesAndSubsets() {

	fmt.Println(Assignment.Size2Subsequence("zxdfoxxxzsszzshhhxhhdxxodhodffxxxxshhozzofhzhdhfoddohzofdsxhddszhhofdxdsfsdszsdxzzfodzoshsdxdsfssoxsofxhszzfffozsfzxzxhsdsxdzoosdofoxdzxhozfdzfhofzhddzfsdfzhxoxohxddhxfxhszfhdsfhfxzzhozxdoshzsfszshdfxsfffxfsososxoshxszzzdzxzdhdxxosfxzxodhdhhsoxoxfxfsdxhzfzhozxzxfhdsofxzffhzzdzdsoxhfzxzzofdfffohzdfszhdhhzdzhzoooxxfhfshofddhxdhfzfhozsfzsszodzzfdfssdxxfxoszzfxdsfzxzofsofosxhsohohszxxodfhhsozshxzsfzdddhhdhfxhfszohdozzosfozxxzoxoxdshxxfsszzodfzdsohfzodzoxoosdhosfxhsxxhzozddffhdodfosdzdxxdfdxhsdszszdofzfdoszzffdshdsxsdsfosoxdzdzzfxxdhdzxzdozhsdzofhfszxoxhzhhhzzfoxsc"))

}